---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, agent, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent, agent, netapp console, console,cloud tier 
summary: 이 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다. 
---
= NetApp 클라우드 계층화 기술 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 클라우드 계층화와 관련된 질문에 대한 빠른 답변을 찾고 있다면 이 FAQ가 도움이 될 수 있습니다.



== 클라우드 티어링 서비스

다음 FAQ는 클라우드 티어링의 작동 방식과 관련이 있습니다.



=== 클라우드 티어링 서비스를 사용하면 어떤 이점이 있나요?

클라우드 티어링은 급격한 데이터 증가로 인해 발생하는 과제를 해결하여 다음과 같은 이점을 제공합니다.

* 클라우드로의 간편한 데이터 센터 확장으로 최대 50배 더 많은 공간 제공
* 저장 최적화로 평균 70%의 저장 공간 절약 효과
* 평균적으로 총 소유 비용이 30% 감소했습니다.
* 애플리케이션을 리팩토링할 필요가 없습니다




=== 어떤 종류의 데이터를 클라우드에 계층화하는 것이 유용합니까?

기본적으로 기본 및 보조 저장 시스템 모두에서 비활성으로 간주되는 모든 데이터는 클라우드로 옮기기에 적합한 대상입니다.  기본 시스템에서 이러한 데이터에는 스냅샷, 과거 기록, 완료된 프로젝트 등이 포함될 수 있습니다.  보조 시스템에서는 DR 및 백업 목적으로 만들어진 기본 데이터의 사본이 들어 있는 모든 볼륨이 여기에 포함됩니다.



=== NAS 볼륨과 SAN 볼륨 모두에서 데이터를 계층화할 수 있나요?

네, StorageGRID 와 같이 NAS 볼륨의 데이터를 퍼블릭 클라우드나 프라이빗 클라우드로 계층화할 수 있습니다.  SAN 프로토콜을 통해 액세스되는 데이터를 계층화하는 경우 NetApp 프라이빗 클라우드를 사용할 것을 권장합니다. SAN 프로토콜은 NAS보다 연결 문제에 더 민감하기 때문입니다.



=== 비활성 데이터 또는 드물게 사용되는 데이터의 정의는 무엇이며, 이는 어떻게 관리됩니까?

콜드 데이터라고도 불리는 것의 정의는 "일정 기간 동안 접근되지 않은 볼륨 블록(메타데이터 제외)"입니다.  "시간"은 cooling-days라는 계층화 정책 속성에 의해 결정됩니다.



=== 클라우드 티어링을 사용하면 클라우드 티어에서 스토리지 효율성 절감 효과가 유지되나요?

네, 압축, 중복 제거, 압축과 같은 ONTAP 볼륨 수준 스토리지 효율성은 데이터를 클라우드 계층으로 이동할 때 유지됩니다.



=== FabricPool 과 Cloud Tiering의 차이점은 무엇인가요?

FabricPool 은 ONTAP CLI 및 System Manager를 통해 자체 관리하거나 Cloud Tiering을 통해 서비스로 관리할 수 있는 ONTAP 계층화 기술입니다.  클라우드 티어링은 FabricPool ONTAP 과 클라우드 모두에서 고급 자동화 프로세스를 갖춘 관리형 서비스로 전환하여 하이브리드 및 멀티 클라우드 배포 전반에서 티어링에 대한 가시성과 제어력을 향상시킵니다.



=== 클라우드에 계층화된 데이터를 재해 복구나 백업/아카이브에 사용할 수 있습니까?

아니요. 볼륨의 메타데이터는 성능 계층에서 계층화되지 않으므로 개체 스토리지에 저장된 데이터에 직접 액세스할 수 없습니다.

그러나 클라우드 티어링을 사용하면 보조 시스템과 SnapMirror 대상 볼륨(DP 볼륨)에서 활성화하여 비용 효율적인 백업 및 재해 복구를 달성하고 모든 데이터(메타데이터 제외)를 계층화하여 데이터 센터 설치 공간과 TCO를 줄일 수 있습니다.



=== 클라우드 티어링은 볼륨 수준에서 적용되나요, 아니면 집계 수준에서 적용되나요?

볼륨별로 계층화 정책을 연결하여 볼륨 수준에서 클라우드 계층화를 활성화할 수 있습니다.  콜드 데이터 식별은 블록 수준에서 수행됩니다.



=== 클라우드 티어링은 어떤 블록을 클라우드에 티어링할지 어떻게 결정합니까?

볼륨과 관련된 계층화 정책은 어떤 블록을 언제 계층화할지 제어하는 메커니즘입니다.  정책은 데이터 블록 유형(스냅샷, 사용자 데이터 또는 둘 다)과 냉각 기간을 정의합니다. 보다link:concept-cloud-tiering.html#volume-tiering-policies["볼륨 티어링 정책"] 자세한 내용은.



=== 클라우드 티어링은 볼륨 용량에 어떤 영향을 미칩니까?

클라우드 티어링은 볼륨의 용량에는 영향을 미치지 않지만 집계된 성능 계층 사용에는 영향을 미칩니다.



=== 클라우드 티어링을 사용하면 비활성 데이터 보고가 가능합니까?

네, 클라우드 티어링은 각 집계에 대해 비활성 데이터 보고(IDR)를 활성화합니다.  이 설정을 사용하면 저비용 개체 스토리지에 계층화할 수 있는 비활성 데이터의 양을 식별할 수 있습니다.



=== IDR을 실행한 순간부터 정보가 표시되기까지 얼마나 걸리나요?

IDR은 구성된 냉각 기간이 지난 후에 정보를 표시하기 시작합니다.  ONTAP 9.7 이하 버전을 사용할 경우 IDR의 냉각 기간은 31일로 조정이 불가능했습니다.  ONTAP 9.8부터 IDR 냉각 기간을 최대 183일까지 구성할 수 있습니다.



== 라이센스 및 비용

다음 FAQ는 클라우드 티어링 사용에 따른 라이선싱 및 비용과 관련이 있습니다.



=== 클라우드 티어링을 사용하는 데 비용이 얼마나 드나요?

콜드 데이터를 퍼블릭 클라우드로 계층화하는 경우:

* 사용량 기반 구독(PAYGO)의 경우: GB당 월 $0.05입니다.
* 연간(BYOL) 기간 기반 구독의 경우, GB/월당 $0.033부터 시작합니다.


https://bluexp.netapp.com/pricing["가격 세부 정보 보기"] .

콜드 데이터를 NetApp StorageGRID 시스템(프라이빗 클라우드)에 계층화할 때는 비용이 발생하지 않습니다.



=== 동일한 ONTAP 클러스터에 대해 BYOL과 PAYGO 라이선스를 모두 가질 수 있나요?

네. 클라우드 티어링을 사용하면 BYOL 라이선스, PAYGO 구독 또는 두 가지를 조합하여 사용할 수 있습니다.



=== BYOL 용량 한도에 도달하거나 BYOL 라이선스가 만료되면 어떻게 되나요?

BYOL 용량 한도에 도달하거나 BYOL 라이선스가 만료되면 새로운 콜드 데이터의 계층화가 중지됩니다.  이전에 계층화된 모든 데이터는 계속 액세스할 수 있습니다. 즉, 이 데이터를 검색하여 사용할 수 있습니다.  검색된 데이터는 클라우드에서 성능 계층으로 다시 이동됩니다.

하지만 _BlueXP - 클라우드 데이터 서비스 배포 및 관리_에 대한 PAYGO 마켓플레이스 구독이 있는 경우 새로운 콜드 데이터는 계속해서 개체 스토리지에 계층화되며 사용량 기준으로 요금을 지불하게 됩니다.



=== 클라우드 티어링 라이선스에 클라우드 제공업체의 이탈 비용이 포함되어 있습니까?

아니, 그렇지 않습니다.



=== 온프레미스 시스템의 재수화는 클라우드 제공자가 청구하는 퇴장 비용의 적용을 받습니까?

네. 퍼블릭 클라우드에서 읽는 모든 작업에는 이탈 수수료가 부과됩니다.



=== 클라우드 요금을 어떻게 추산할 수 있나요?  클라우드 티어링에 대한 "만약" 모드가 있나요?

클라우드 제공업체가 데이터 호스팅에 대해 청구할 금액을 추정하는 가장 좋은 방법은 해당 업체의 계산기를 사용하는 것입니다. https://calculator.aws/#/["AWS"] , https://azure.microsoft.com/en-us/pricing/calculator/["하늘빛"] 그리고 https://cloud.google.com/products/calculator["구글 클라우드"] .



=== 클라우드 제공업체가 개체 스토리지에서 온프레미스 스토리지로 데이터를 읽거나 검색할 때 추가 비용을 청구합니까?



=== 클라우드 제공업체가 개체 스토리지에서 온프레미스 스토리지로 데이터를 읽거나 검색할 때 추가 비용을 청구합니까?

네. 확인하다 https://aws.amazon.com/s3/pricing/["Amazon S3 가격"] , https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["블록 블롭 가격"] , 그리고 https://cloud.google.com/storage/pricing["클라우드 스토리지 가격"] 데이터 읽기/검색에 따른 추가 가격이 부과됩니다.



=== 클라우드 티어링을 활성화하기 전에 볼륨 절감액을 추산하고 콜드 데이터 보고서를 받으려면 어떻게 해야 합니까?

추정치를 얻으려면 ONTAP 클러스터를 NetApp 콘솔에 추가하고 클라우드 계층화 클러스터 페이지를 통해 검사하세요.  클러스터를 시작하려면 *잠재적 계층화 절감 계산*을 선택하세요. https://bluexp.netapp.com/cloud-tiering-service-tco["클라우드 티어링 TCO 계산기"^] 얼마나 많은 돈을 절약할 수 있는지 확인해 보세요.



=== ONTAP MetroCluster 사용할 때 계층화 요금은 어떻게 청구됩니까?

MetroCluster 환경에서 사용하는 경우 전체 계층화 라이선스가 두 클러스터 모두에 적용됩니다.  예를 들어, 100TiB의 계층화 라이선스가 있는 경우 각 클러스터의 사용된 계층화 용량은 총 100TiB 용량에 포함됩니다.



== ONTAP

다음 질문은 ONTAP 과 관련이 있습니다.



=== Cloud Tiering은 어떤 ONTAP 버전을 지원합니까?

클라우드 티어링은 ONTAP 버전 9.2 이상을 지원합니다.



=== 어떤 유형의 ONTAP 시스템이 지원됩니까?

클라우드 티어링은 단일 노드 및 고가용성 AFF, FAS, ONTAP Select 클러스터에서 지원됩니다.  FabricPool Mirror 구성과 MetroCluster 구성의 클러스터도 지원됩니다.



=== HDD만으로 FAS 시스템의 데이터를 계층화할 수 있나요?

네, ONTAP 9.8부터 HDD 집계에 호스팅된 볼륨의 데이터를 계층화할 수 있습니다.



=== HDD가 있는 FAS 노드가 있는 클러스터에 가입된 AFF 에서 데이터를 계층화할 수 있나요?

네. 클라우드 티어링은 모든 집계에 호스팅된 볼륨을 계층화하도록 구성할 수 있습니다.  데이터 계층 구성은 사용된 컨트롤러 유형이나 클러스터가 이기종인지 여부와 관련이 없습니다.



=== Cloud Volumes ONTAP 은 어떤가요?

Cloud Volumes ONTAP 시스템이 있는 경우 클라우드 계층화 클러스터 페이지에서 해당 시스템을 찾을 수 있으며, 이를 통해 하이브리드 클라우드 인프라의 데이터 계층화를 전체적으로 파악할 수 있습니다.  하지만 Cloud Volumes ONTAP 시스템은 Cloud Tiering에서 읽기 전용입니다.  Cloud Tiering에서 Cloud Volumes ONTAP 에 데이터 계층화를 설정할 수 없습니다. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["NetApp 콘솔의 ONTAP 시스템에서 Cloud Volumes ONTAP 시스템에 대한 계층화를 설정합니다."^] .



=== ONTAP 클러스터에 필요한 다른 요구 사항은 무엇입니까?

이는 콜드 데이터를 어디에 계층화하느냐에 따라 달라집니다.  자세한 내용은 다음 링크를 참조하세요.

* link:task-tiering-onprem-aws.html#prepare-your-ontap-cluster["Amazon S3에 데이터 계층화"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["Azure Blob 스토리지에 데이터 계층화"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["Google Cloud Storage에 데이터 계층화"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["StorageGRID 에 데이터 계층화"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["S3 개체 스토리지에 데이터 계층화"]




== 객체 스토리지

다음 질문은 객체 스토리지와 관련이 있습니다.



=== 어떤 객체 스토리지 공급자가 지원되나요?

Cloud Tiering은 다음과 같은 개체 스토리지 공급자를 지원합니다.

* 아마존 S3
* 마이크로소프트 애저 블롭
* 구글 클라우드 스토리지
* NetApp StorageGRID
* S3 호환 객체 스토리지(예: MinIO)
* IBM Cloud Object Storage( FabricPool 구성은 System Manager 또는 ONTAP CLI를 사용하여 수행해야 함)




=== 내 버킷/용기를 사용할 수 있나요?

네, 가능합니다. 데이터 계층화를 설정할 때 새 버킷/컨테이너를 추가하거나 기존 버킷/컨테이너를 선택할 수 있습니다.



=== 어떤 지역이 지원되나요?

* link:reference-aws-support.html["지원되는 AWS 지역"]
* link:reference-azure-support.html["지원되는 Azure 지역"]
* link:reference-google-support.html["지원되는 Google Cloud 지역"]




=== 어떤 S3 스토리지 클래스가 지원되나요?

클라우드 티어링은 _표준_, _표준-빈번하지 않은 액세스_, _단일 영역-빈번하지 않은 액세스_, _지능형 티어링_, _Glacier 즉시 검색_ 스토리지 클래스에 대한 데이터 티어링을 지원합니다. 보다link:reference-aws-support.html["지원되는 S3 스토리지 클래스"] 자세한 내용은.



=== Amazon S3 Glacier Flexible과 S3 Glacier Deep Archive가 Cloud Tiering에서 지원되지 않는 이유는 무엇입니까?

Amazon S3 Glacier Flexible과 S3 Glacier Deep Archive가 지원되지 않는 주된 이유는 Cloud Tiering이 고성능 계층화 솔루션으로 설계되었기 때문에 데이터를 지속적으로 사용할 수 있어야 하고 검색을 위해 빠르게 액세스할 수 있어야 하기 때문입니다.  S3 Glacier Flexible과 S3 Glacier Deep Archive를 사용하면 데이터 검색에 몇 분에서 최대 48시간까지 걸릴 수 있습니다.



=== MinIO와 같은 다른 S3 호환 개체 스토리지 서비스를 Cloud Tiering과 함께 사용할 수 있나요?

네, ONTAP 9.8 이상을 사용하는 클러스터에서는 Tiering UI를 통해 S3 호환 개체 스토리지를 구성할 수 있습니다. link:task-tiering-onprem-s3-compat.html["자세한 내용은 여기에서 확인하세요"] .



=== 어떤 Azure Blob 액세스 계층이 지원되나요?

클라우드 티어링은 비활성 데이터에 대해 _핫_ 또는 _쿨_ 액세스 계층으로의 데이터 티어링을 지원합니다. 보다link:reference-azure-support.html["지원되는 Azure Blob 액세스 계층"] 자세한 내용은.



=== Google Cloud Storage에서는 어떤 스토리지 클래스가 지원되나요?

클라우드 티어링은 _Standard_, _Nearline_, _Coldline_, _Archive_ 스토리지 클래스에 대한 데이터 티어링을 지원합니다. 보다link:reference-google-support.html["지원되는 Google Cloud 스토리지 클래스"] 자세한 내용은.



=== 클라우드 티어링은 수명 주기 관리 정책 사용을 지원합니까?

네. 특정 기간이 지난 후 Cloud Tiering이 기본 스토리지 클래스/액세스 계층의 데이터를 더 비용 효율적인 계층으로 전환하도록 수명 주기 관리를 활성화할 수 있습니다.  수명 주기 규칙은 Amazon S3 및 Google Cloud Storage의 경우 선택된 버킷에 있는 모든 개체에 적용되고, Azure Blob의 경우 선택된 스토리지 계정의 모든 컨테이너에 적용됩니다.



=== 클라우드 티어링은 전체 클러스터에 하나의 개체 저장소를 사용하나요, 아니면 집계당 하나씩 사용하나요?

일반적인 구성에서는 클러스터 전체에 대해 하나의 개체 저장소가 있습니다.  2022년 8월부터 *고급 설정* 페이지를 사용하여 클러스터에 대한 추가 개체 저장소를 추가한 다음, 다른 개체 저장소를 다른 집계에 연결하거나 미러링을 위해 2개의 개체 저장소를 집계에 연결할 수 있습니다.



=== 동일한 집계에 여러 개의 버킷을 첨부할 수 있나요?

미러링을 목적으로 집계당 최대 2개의 버킷을 연결할 수 있으며, 이때 콜드 데이터는 두 버킷 모두에 동기적으로 계층화됩니다.  버킷은 다양한 공급업체와 위치에서 제공될 수 있습니다.  2022년 8월부터 *고급 설정* 페이지를 사용하여 두 개의 개체 저장소를 단일 집계에 연결할 수 있습니다.



=== 동일한 클러스터 내의 서로 다른 집계에 서로 다른 버킷을 첨부할 수 있나요?

네. 일반적으로 가장 좋은 방법은 하나의 버킷을 여러 개의 집계에 연결하는 것입니다.  그러나 퍼블릭 클라우드를 사용하는 경우 개체 스토리지 서비스에 대한 최대 IOPS 제한이 있으므로 여러 버킷을 고려해야 합니다.



=== 한 클러스터에서 다른 클러스터로 볼륨을 마이그레이션하면 계층화된 데이터는 어떻게 되나요?

한 클러스터에서 다른 클러스터로 볼륨을 마이그레이션할 때 모든 콜드 데이터는 클라우드 계층에서 읽혀집니다.  대상 클러스터의 쓰기 위치는 계층화가 활성화되었는지 여부와 소스 및 대상 볼륨에서 사용된 계층화 정책 유형에 따라 달라집니다.



=== 동일한 클러스터 내에서 볼륨을 한 노드에서 다른 노드로 이동하면 계층화된 데이터는 어떻게 되나요?

대상 집계에 연결된 클라우드 계층이 없으면 소스 집계의 클라우드 계층에서 데이터를 읽어 대상 집계의 로컬 계층에 전부 씁니다.  대상 집계에 연결된 클라우드 계층이 있는 경우 소스 집계의 클라우드 계층에서 데이터를 읽어 대상 집계의 로컬 계층에 먼저 기록하여 빠른 전환을 용이하게 합니다.  나중에 사용된 계층화 정책에 따라 클라우드 계층에 기록됩니다.

ONTAP 9.6부터 대상 집계가 소스 집계와 동일한 클라우드 계층을 사용하는 경우 콜드 데이터는 로컬 계층으로 다시 이동하지 않습니다.



=== 계층화된 데이터를 온프레미스의 성능 계층으로 다시 가져오려면 어떻게 해야 합니까?

쓰기 백업은 일반적으로 읽기에서 수행되며 계층화 정책 유형에 따라 달라집니다.  ONTAP 9.8 이전에는 _볼륨 이동_ 작업을 통해 전체 볼륨을 다시 쓸 수 있었습니다.  ONTAP 9.8부터 계층화 UI에 *모든 데이터 다시 가져오기* 또는 *활성 파일 시스템 다시 가져오기* 옵션이 추가되었습니다. link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["데이터를 성능 계층으로 다시 이동하는 방법 보기"] .



=== 기존 AFF/ FAS 컨트롤러를 새 컨트롤러로 교체할 때, 계층화된 데이터가 온프레미스로 다시 마이그레이션됩니까?

아니요. "헤드 스왑" 절차 동안 변경되는 것은 집계된 소유권뿐입니다.  이 경우, 데이터 이동 없이 새로운 컨트롤러로 변경됩니다.



=== 클라우드 제공업체의 콘솔이나 개체 스토리지 탐색기를 사용하여 버킷에 계층화된 데이터를 볼 수 있나요?  ONTAP 없이도 객체 스토리지에 저장된 데이터를 직접 사용할 수 있나요?

아니요. 클라우드에 생성되어 계층화된 객체는 단일 파일을 포함하지 않고 여러 파일에서 최대 1,024개의 4KB 블록을 포함합니다.  볼륨의 메타데이터는 항상 로컬 계층에 남아 있습니다.



== 콘솔 에이전트

다음 질문은 콘솔 에이전트와 관련이 있습니다.



=== 콘솔 에이전트란 무엇인가요?

콘솔 에이전트는 클라우드 계정 내부 또는 온프레미스의 컴퓨팅 인스턴스에서 실행되는 소프트웨어로, NetApp 콘솔이 클라우드 리소스를 안전하게 관리할 수 있도록 해줍니다.  클라우드 티어링 서비스를 사용하려면 에이전트를 배포해야 합니다.



=== 콘솔 에이전트는 어디에 설치해야 합니까?

* 데이터를 S3에 계층화하면 에이전트는 AWS VPC나 고객사 내에 상주할 수 있습니다.
* 데이터를 Blob 저장소에 계층화하면 에이전트는 Azure VNet이나 온프레미스에 상주할 수 있습니다.
* Google Cloud Storage에 데이터를 계층화하는 경우 에이전트는 Google Cloud Platform VPC에 있어야 합니다.
* 데이터를 StorageGRID 또는 다른 S3 호환 스토리지 공급자에 계층화하는 경우 에이전트는 회사 내에 있어야 합니다.




=== 온프레미스에 콘솔 에이전트를 배포할 수 있나요?

네. 에이전트 소프트웨어는 네트워크의 Linux 호스트에 다운로드하여 수동으로 설치할 수 있습니다. https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["귀하의 건물에 에이전트를 설치하는 방법을 확인하세요"] .



=== Cloud Tiering을 사용하려면 클라우드 서비스 제공업체 계정이 필요합니까?

네. 사용하려는 개체 스토리지를 정의하려면 먼저 계정이 있어야 합니다.  VPC 또는 VNet에서 클라우드에 에이전트를 설정하는 경우에도 클라우드 스토리지 공급자의 계정이 필요합니다.



=== 콘솔 에이전트가 실패하면 어떤 영향이 있나요?

에이전트에 장애가 발생하는 경우, 계층화된 환경에 대한 가시성만 영향을 받습니다.  모든 데이터에 접근할 수 있으며, 새로 식별된 콜드 데이터는 자동으로 개체 스토리지에 계층화됩니다.



== 계층화 정책



=== 사용 가능한 티어링 정책은 무엇입니까?

4가지 계층화 정책이 있습니다.

* 없음: 모든 데이터를 항상 핫으로 분류하여 볼륨의 모든 데이터가 개체 스토리지로 이동되지 않도록 합니다.
* 콜드 스냅샷(스냅샷 전용): 콜드 스냅샷 블록만 개체 스토리지로 이동됩니다.
* 콜드 사용자 데이터 및 스냅샷(자동): 콜드 스냅샷 블록과 콜드 사용자 데이터 블록은 모두 개체 스토리지로 이동됩니다.
* 모든 사용자 데이터(전체): 모든 데이터를 콜드 데이터로 분류하고 전체 볼륨을 즉시 개체 스토리지로 이동합니다.


link:concept-cloud-tiering.html#volume-tiering-policies["티어링 정책에 대해 자세히 알아보세요"] .



=== 어느 시점에서 내 데이터가 콜드 데이터로 간주되나요?

데이터 계층화는 블록 수준에서 이루어지므로, 계층화 정책의 최소 냉각 일수 속성에 의해 정의된 일정 기간 동안 액세스되지 않은 데이터 블록은 콜드 상태로 간주됩니다.  적용 범위는 ONTAP 9.7 이하에서는 2~63일이 적용되고, ONTAP 9.8부터는 2~183일이 적용됩니다.



=== 데이터가 클라우드 계층으로 분류되기 전의 기본 냉각 기간은 얼마입니까?

콜드 스냅샷 정책의 기본 쿨링 기간은 2일이고, 콜드 사용자 데이터 및 스냅샷의 기본 쿨링 기간은 31일입니다.  냉각일 매개변수는 모든 계층화 정책에 적용되지 않습니다.



=== 전체 백업을 수행하면 모든 계층화된 데이터가 개체 스토리지에서 검색됩니까?

전체 백업 중에는 모든 콜드 데이터를 읽습니다.  데이터 검색은 사용된 계층화 정책에 따라 달라집니다.  모든 사용자 데이터 및 스냅샷 정책을 사용하는 경우 콜드 데이터는 성능 계층에 다시 기록되지 않습니다.  콜드 스냅샷 정책을 사용하는 경우 백업에 이전 스냅샷이 사용되는 경우에만 콜드 블록이 검색됩니다.



=== 볼륨별로 계층화 크기를 선택할 수 있나요?

아니요. 하지만 계층화에 적합한 볼륨, 계층화할 데이터 유형 및 쿨링 기간은 선택할 수 있습니다.  이는 해당 볼륨에 계층화 정책을 연결하여 수행됩니다.



=== 모든 사용자 데이터 정책이 데이터 보호 볼륨에 대한 유일한 옵션입니까?

아니요. 데이터 보호(DP) 볼륨은 사용 가능한 세 가지 정책 중 하나와 연관될 수 있습니다.  소스 및 대상(DP) 볼륨에 사용되는 정책 유형은 데이터의 쓰기 위치를 결정합니다.



=== 볼륨의 계층화 정책을 없음으로 재설정하면 콜드 데이터가 다시 활성화되나요? 아니면 향후 콜드 블록이 클라우드로 이동되지 않게 되나요?

계층화 정책이 재설정되면 재수화는 일어나지 않지만 새로운 콜드 블록이 클라우드 계층으로 이동되는 것은 방지됩니다.



=== 데이터를 클라우드에 계층화한 후 계층화 정책을 변경할 수 있나요?

네. 변경 후의 동작은 연관된 새 정책에 따라 달라집니다.



=== 특정 데이터가 클라우드로 이동되지 않도록 하려면 어떻게 해야 합니까?

해당 데이터가 포함된 볼륨에 계층화 정책을 연결하지 마세요.



=== 파일의 메타데이터는 어디에 저장되나요?

볼륨의 메타데이터는 항상 성능 계층에 로컬로 저장되며, 클라우드에 계층화되지 않습니다.



== 네트워킹 및 보안

다음 질문은 네트워킹과 보안과 관련이 있습니다.



=== 네트워킹 요구 사항은 무엇입니까?

* ONTAP 클러스터는 포트 443을 통해 개체 스토리지 공급자에 HTTPS 연결을 시작합니다.
+
ONTAP 객체 스토리지에서 데이터를 읽고 씁니다.  객체 스토리지는 결코 시작되지 않고, 단지 응답만 합니다.

* StorageGRID 의 경우 ONTAP 클러스터는 사용자가 지정한 포트를 통해 StorageGRID 에 HTTPS 연결을 시작합니다(포트는 계층화 설정 중에 구성 가능).
* 에이전트는 ONTAP 클러스터, 개체 저장소 및 Cloud Tiering 서비스에 대한 포트 443을 통한 아웃바운드 HTTPS 연결이 필요합니다.


자세한 내용은 다음을 참조하세요.

* link:task-tiering-onprem-aws.html["Amazon S3에 데이터 계층화"]
* link:task-tiering-onprem-azure.html["Azure Blob 스토리지에 데이터 계층화"]
* link:task-tiering-onprem-gcp.html["Google Cloud Storage에 데이터 계층화"]
* link:task-tiering-onprem-storagegrid.html["StorageGRID 에 데이터 계층화"]
* link:task-tiering-onprem-s3-compat.html["S3 개체 스토리지에 데이터 계층화"]




=== 클라우드에 저장된 콜드 데이터를 관리하기 위해 모니터링 및 보고에 어떤 도구를 사용할 수 있나요?

클라우드 티어링 외에도 https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^] 그리고 https://docs.netapp.com/us-en/active-iq/index.html["디지털 어드바이저"^] 모니터링 및 보고에 사용할 수 있습니다.



=== 클라우드 공급자와의 네트워크 링크가 끊어지면 어떤 영향이 있나요?

네트워크 장애가 발생하는 경우 로컬 성능 계층은 온라인 상태를 유지하고, 핫 데이터는 계속 액세스할 수 있습니다.  그러나 이미 클라우드 계층으로 이동된 블록에는 액세스할 수 없으며, 애플리케이션은 해당 데이터에 액세스하려고 하면 오류 메시지를 받게 됩니다.  연결이 복구되면 모든 데이터에 원활하게 접근할 수 있습니다.



=== 네트워크 대역폭 권장 사항이 있나요?

기본 FabricPool 계층화 기술의 읽기 지연 시간은 클라우드 계층에 대한 연결성에 따라 달라집니다.  계층화는 모든 대역폭에서 작동하지만 적절한 성능을 제공하려면 10Gbps 포트에 클러스터 간 LIF를 배치하는 것이 좋습니다.  에이전트에 대한 권장 사항이나 대역폭 제한은 없습니다.

또한 볼륨에서 개체 스토리지로 비활성 데이터를 전송하는 동안 사용되는 네트워크 대역폭 양을 조절할 수 있습니다.  _최대 전송 속도_ 설정은 클러스터를 계층화할 때 사용할 수 있으며, 나중에 *클러스터* 페이지에서 사용할 수 있습니다.



=== 사용자가 계층화된 데이터에 액세스하려고 할 때 지연이 발생합니까?

네. 클라우드 계층은 연결성에 따라 지연 시간이 달라지므로 로컬 계층과 동일한 지연 시간을 제공할 수 없습니다.  객체 저장소의 대기 시간과 처리량을 추정하기 위해 Cloud Tiering은 객체 저장소가 연결된 후 계층화가 설정되기 전에 사용할 수 있는 클라우드 성능 테스트( ONTAP 객체 저장소 프로파일러 기반)를 제공합니다.



=== 내 데이터는 어떻게 보호되나요?

AES-256-GCM 암호화는 성능 및 클라우드 계층 모두에서 유지됩니다.  TLS 1.2 암호화는 계층 간을 이동하는 데이터를 암호화하고, 에이전트와 ONTAP 클러스터 및 개체 저장소 간의 통신을 암호화하는 데 사용됩니다.



=== AFF 에 이더넷 포트를 설치하고 구성해야 합니까?

네. HA 쌍 내의 각 노드에서, 클라우드로 계층화할 데이터가 있는 볼륨을 호스팅하는 이더넷 포트에 클러스터 간 LIF를 구성해야 합니다.  자세한 내용은 데이터를 계층화하려는 클라우드 공급자의 요구 사항 섹션을 참조하세요.



=== 어떤 권한이 필요합니까?

* link:task-tiering-onprem-aws.html#set-up-s3-permissions["Amazon의 경우 S3 버킷을 관리하려면 권한이 필요합니다."] .
* Azure의 경우 NetApp 콘솔에 제공해야 하는 권한 외에 추가 권한은 필요하지 않습니다.
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["Google Cloud의 경우 스토리지 액세스 키가 있는 서비스 계정에 스토리지 관리자 권한이 필요합니다."] .
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["StorageGRID 의 경우 S3 권한이 필요합니다."] .
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["S3 호환 개체 스토리지의 경우 S3 권한이 필요합니다."] .

