---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: NetApp Cloud Tiering 의 새로운 기능을 알아보세요. 
---
= NetApp Cloud Tiering 의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Cloud Tiering 의 새로운 기능을 알아보세요.



== 2025년 10월 6일



=== BlueXP tiering 이제 NetApp Cloud Tiering 입니다.

BlueXP tiering 이 NetApp Cloud Tiering 으로 변경되었습니다.



=== BlueXP 는 이제 NetApp Console 입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경에서 NetApp 스토리지와 NetApp Data Services 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Console 릴리스 노트"] .



== 2023년 8월 9일



=== 버킷 이름에 사용자 정의 접두사를 사용하세요

이전에는 버킷 이름을 정의할 때 기본 "fabric-pool" 접두사(예: _fabric-pool-bucket1_)를 사용해야 했습니다. 이제 버킷 이름을 지정할 때 사용자 지정 접두사를 사용할 수 있습니다. 이 기능은 Amazon S3에 데이터를 계층화할 때만 사용할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["자세히 알아보기"] .



=== 모든 BlueXP 커넥터에서 클러스터 검색

사용자 환경의 모든 스토리지 시스템을 관리하기 위해 여러 개의 커넥터를 사용하는 경우, 계층화를 구현하려는 일부 클러스터가 서로 다른 커넥터에 있을 수 있습니다. 특정 클러스터를 관리하는 커넥터가 무엇인지 확실하지 않은 경우 Cloud Tiering을 사용하여 모든 커넥터를 검색할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["자세히 알아보기"] .



== 2023년 7월 4일



=== 비활성 데이터를 전송하기 위해 대역폭을 조정합니다.

클라우드 티어링을 활성화하면 ONTAP 무제한의 네트워크 대역폭을 사용하여 클러스터의 볼륨에서 비활성 데이터를 개체 스토리지로 전송할 수 있습니다. 계층화된 트래픽이 일반 사용자 작업 부하에 영향을 미치는 경우 전송 중에 사용할 수 있는 대역폭 양을 조절할 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["자세히 알아보기"] .



=== 알림 센터에 표시되는 티어링 이벤트

클러스터가 콜드 데이터의 20% 미만을 계층화하는 경우(데이터를 계층화하지 않는 클러스터 포함) 계층화 이벤트 "클러스터 <이름>에서 개체 스토리지로 추가 데이터를 계층화하여 스토리지 효율성을 높이세요"가 이제 알림으로 표시됩니다.

이 알림은 귀하의 시스템 효율성을 높이고 저장 비용을 절감하는 데 도움이 되는 "권장 사항"입니다. 링크를 제공합니다 https://bluexp.netapp.com/cloud-tiering-service-tco["클라우드 티어링 총 소유 비용 및 절감 계산기"^] 비용 절감액을 계산하는 데 도움이 됩니다.



== 2023년 4월 3일



=== 라이센스 탭이 제거되었습니다.

클라우드 티어링 인터페이스에서 라이선싱 탭이 제거되었습니다.  이제 모든 Pay-as-you-go(PAYGO) 구독 라이선싱에 온프레미스 클라우드 계층화 대시보드에서 액세스할 수 있습니다.  해당 페이지에서는 BlueXP digital wallet 으로 연결되는 링크도 있어서 클라우드 계층화의 BYOL(Bring-Your-Own-Licenses)을 보고 관리할 수 있습니다.



=== 계층화 탭의 이름이 변경되고 업데이트되었습니다.

"클러스터 대시보드" 탭의 이름이 "클러스터"로 바뀌었고, "온프레미스 개요" 탭의 이름이 "온프레미스 대시보드"로 바뀌었습니다.  이 페이지에는 추가 계층 구성으로 저장 공간을 최적화할 수 있는지 평가하는 데 도움이 되는 정보가 추가되었습니다.



== 2023년 3월 5일



=== 볼륨에 대한 계층화 보고서 생성

관리 중인 클러스터의 모든 볼륨에 대한 계층화 상태를 검토할 수 있도록 Tier Volumes 페이지에서 보고서를 다운로드할 수 있습니다.  BlueXP Tiering은 필요에 따라 회사의 다른 사람들에게 검토하고 보낼 수 있는 .CSV 파일을 생성합니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["티어링 보고서를 다운로드하는 방법을 확인하세요"] .



== 2022년 12월 6일



=== 커넥터 아웃바운드 인터넷 액세스 엔드포인트 변경

Cloud Tiering이 변경되어 Cloud Tiering 작업을 성공적으로 수행하려면 다음 커넥터 엔드포인트를 변경해야 합니다.

[cols="50,50"]
|===
| 이전 엔드포인트 | 새로운 엔드포인트 


| \ https://cloudmanager.cloud.netapp.com | \ https://api.bluexp.netapp.com 


| \https://*.cloudmanager.cloud.netapp.com | \https://*.api.bluexp.netapp.com 
|===
귀하의 엔드포인트 전체 목록을 확인하세요. https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^] , https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["구글 클라우드"^] , 또는 https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["하늘빛"^] 클라우드 환경.



== 2022년 11월 6일



=== 드래그 앤 드롭으로 추가 목적지로의 계층화를 활성화합니다.

Canvas에 Azure Blob, Google Cloud Storage 또는 StorageGRID 계층화 대상이 작업 환경으로 존재하는 경우 온-프레미스 ONTAP 작업 환경을 대상으로 끌어서 계층화 설정 마법사를 시작할 수 있습니다.



== 2022년 9월 19일



=== Amazon S3에 티어링할 때 AWS PrivateLink 구성

이전 릴리스에서는 VPC 엔드포인트를 통해 클러스터를 S3 버킷에 연결하는 안전한 방법을 제공하는 데 많은 시간이 소요되었습니다.  이제 필수 단계를 따라갈 수 있습니다. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["VPC 엔드포인트 인터페이스를 사용하여 개인 연결을 위해 시스템을 구성합니다."] 그런 다음 네트워킹 페이지에서 계층화 설정 마법사를 실행하는 동안 PrivateLink를 선택할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["비활성 데이터를 Amazon S3에 계층화하기 위한 요구 사항 및 단계를 검토하세요."].



=== Amazon S3에 계층화를 활성화하려면 드래그 앤 드롭하세요.

Amazon S3 계층화 대상이 Canvas에 작업 환경으로 존재하는 경우 온-프레미스 ONTAP 작업 환경을 대상으로 끌어서 놓아 계층화 설정 마법사를 시작할 수 있습니다.



=== 미러 객체 저장소를 제거할 때 계층화 동작을 선택하세요.

MetroCluster 구성에서 미러 개체 저장소를 제거할 때 기본 개체 저장소도 제거할지 여부를 묻는 메시지가 표시됩니다.  기본 개체 저장소를 집계에 연결된 상태로 유지하거나 제거할 수 있습니다.



== 2022년 8월 3일



=== 다른 집계에 대한 추가 개체 저장소 구성

클라우드 계층화 UI에 개체 스토리지 구성을 위한 새로운 페이지 세트가 추가되었습니다.  새로운 객체 저장소를 추가하고, FabricPool 미러링을 위해 여러 객체 저장소를 집계에 연결하고, 기본 및 미러 객체 저장소를 교체하고, 집계에 대한 객체 저장소 연결을 삭제하는 등의 작업이 가능합니다. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["새로운 객체 스토리지 기능에 대해 자세히 알아보세요."]



=== MetroCluster 구성에 대한 라이센스 지원

이제 Cloud Tiering 라이선스를 MetroCluster 구성의 클러스터와 공유할 수 있습니다.  이러한 시나리오에서는 더 이상 사용되지 않는 FabricPool 라이선스를 사용할 필요가 없습니다.  이를 통해 더 많은 클러스터에서 "플로팅" 클라우드 티어링 라이선스를 사용하기가 더 쉬워집니다. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["이러한 유형의 클러스터에 대한 라이선스를 부여하고 구성하는 방법을 알아보세요."]
